name: Version Bump

permissions:
  id-token: write  # Required for OIDC
  contents: write

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-bump:
    runs-on: ubuntu-latest
    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@v6.0.1
      with:
        fetch-depth: 0
        fetch-tags: true
    
    - name: 📦 Enable Corepack
      run: corepack enable

    - name: 🏗 Setup Node
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: yarn
        
    - name: 📦 Install Project dependencies
      run: yarn install --immutable
      
    - name: 🏗️ Build packages
      run: yarn build

    - name: 🏗️ Test packages
      run: yarn test
      
    - name: 🤜 Bump Please
      uses: chriswoodle/bump-please-action@v1.0.1
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}

    - name: 📦 Publish bump-please-core
      run: cd bump-please-core && yarn npm publish --access public

    - name: 📦 Publish bump-please
      run: cd bump-please && yarn npm publish --access public
    