name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: 🏗 Setup repo
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

    - name: 📦 Enable Corepack
      run: corepack enable

    - name: 🏗 Setup Node
      uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
      with:
        node-version: 24
        cache: yarn

    - name: 📦 Install Project dependencies
      run: yarn install --immutable

    - name: 🏗️ Build packages
      run: yarn build

    - name: 🏗️ Build action
      run: yarn build:action

    - name: 🏗️ Test packages
      run: yarn test
